### ISSUE TITLE
2.7.2 prefix install fails

### ISSUE THREAD

**Issue by stefanozampini** [coin-or/ADOL-C#20]
I can successfully make and install the C/C++ library, but then, the install rule eventually fails when running `make install` in the swig directory and I get the error below (prefix is not propagated)
Also, I do not need the python wrappers, bu  I do not see how I can disable it from configure

```
$ ./configure --prefix=someprefix --enable-shared --enable-sparse
$ make
$ make install
...
Making install in swig
gmake[4]: Entering directory '/home/szampini/Devel/jointinversion/pkgs/petsc/arch-joint/externalpackages/ADOL-C-2.7.2/ADOL-C/swig'
CXX=mpicxx /usr/bin/python setup.py install --prefix=/home/szampini/Devel/jointinversion/pkgs/petsc/arch-joint --only-swig
running install
running build
running build_lib
skipping build of ADOL-C
running build_ext
prefix =  /home/szampini/adolc_base
```

**Comment by awalther1** [comment]
Hi, we had this problem with the releases 2.7.0 and 2.7.1. This should be fixed now.

**Comment by stefanozampini** [comment]
This has not been fixed (tried today, still same error)

**Comment by stefanozampini** [comment]
@awalther1

**Comment by awalther1** [comment]
Hi, we had an issue with the prefix that was fixed in 2.7.2. I thought this had solved also your problem. However, this seems not to be the case. We will now have a look at your specific problem.
Best regards

Andrea

**Comment by stefanozampini** [comment]
https://github.com/coin-or/ADOL-C/blob/master/configure.ac#L663

it should be `test` and not `$test`

I tried with `master` and it works as expected. We should temporarily track the dev branch in our package and start using releases from the next one.
Anyway, it would be nice if you provide --enable-python as configure flag in the next releases to allow for users to disable the python build

**Comment by stefanozampini** [comment]
Sorry, not yet completely fixed. I spoke too early. This is with the latest master 

configure (note the libdir)

```
./configure --prefix=/home/szampini/Devel/petsc/arch-maint MAKE=/usr/bin/gmake --libdir=/home/szampini/Devel/petsc/arch-maint/lib CC="mpicc" CFLAGS="-g -O0 -fPIC" AR="/usr/bin/ar" ARFLAGS="cr" CXX="mpicxx" CXXFLAGS="-g -O0 -fPIC" F90="mpif90" F90FLAGS="-g -O0 -fPIC" FFLAGS="-g -O0 -fPIC" FC="mpif90" F77="mpif90" FCFLAGS="-g -O0 -fPIC" --enable-shared --enable-sparse
```

When running make install, the swig build uses the suffix `lib64` as location for adolc (libdir is not respected) and fails.

```
...
compile options: '-I/usr/lib64/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m -I/home/szampini/Devel/petsc/arch-maint/include -c'
extra options: '-std=c++11 -fPIC -w'
gcc: adolc-python_wrap.cpp
mpicxx -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g build/temp.linux-x86_64-3.7/adolc-python_wrap.o -L/usr/lib64 -L/home/szampini/Devel/petsc/arch-maint/lib64 -Wl,--enable-new-dtags,-R/home/szampini/Devel/petsc/arch-maint/lib64 -ladolc -lpython3.7m -o build/lib.linux-x86_64-3.7/_adolc.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -ladolc
collect2: error: ld returned 1 exit status
error: Command "mpicxx -pthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -g build/temp.linux-x86_64-3.7/adolc-python_wrap.o -L/usr/lib64 -L/home/szampini/Devel/petsc/arch-maint/lib64 -Wl,--enable-new-dtags,-R/home/szampini/Devel/petsc/arch-maint/lib64 -ladolc -lpython3.7m -o build/lib.linux-x86_64-3.7/_adolc.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1

```

**Comment by awalther1** [comment]
Hi, thanks a lot for the additional information. We will try to fix this as soon as possible.

**Comment by caidao22** [comment]
Hi, this issue has been hanging fire for over six months. Is there a plan for fixing it soon?

**Comment by awalther1** [comment]
Hi,

> it should be test and not $test

this is fixed now in the master

>  --enable-python as configure flag 

this is now provided, by default it is disabled, disabling also the swif build

we still have to fix the problem with the  suffix lib64 as location for the swig build

It woudl be great if you coudl give it a try

**Comment by awalther1** [comment]
This should be reallyy fixed now.

**Comment by stefanozampini** [comment]
Thanks. However, it is not completely fixed, since you did not commit the new `configure` file. I had to rerun `autoconf` to have the python script disabled by default

**Comment by awalther1** [comment]
Thanks for the hint, I commited the corresponding configure file a few minutes ago
